import { Spot, Itinerary, ItineraryDay, ItineraryItem } from "@/types";

// ===== SPOTS (Tokyo) =====

export const SAMPLE_SPOTS: Spot[] = [
  {
    id: "spot-meiji",
    nameEn: "Meiji Jingu Shrine",
    nameJa: "明治神宮",
    description: "A serene Shinto shrine in the heart of Tokyo, surrounded by a lush forest. Dedicated to Emperor Meiji and Empress Shoken.",
    category: "shrine",
    area: "tokyo",
    lat: 35.6764,
    lng: 139.6993,
    address: "1-1 Yoyogikamizonocho, Shibuya City, Tokyo",
    photoUrls: [],
    admissionFee: "Free",
    avgDurationMin: 60,
  },
  {
    id: "spot-takeshita",
    nameEn: "Takeshita Street",
    nameJa: "竹下通り",
    description: "A vibrant pedestrian street in Harajuku famous for trendy shops, quirky fashion, crepe stands, and youth culture.",
    category: "shopping",
    area: "tokyo",
    lat: 35.6702,
    lng: 139.7026,
    address: "Jingumae, Shibuya City, Tokyo",
    photoUrls: [],
    avgDurationMin: 75,
  },
  {
    id: "spot-shibuya",
    nameEn: "Shibuya Crossing & Hachiko",
    nameJa: "渋谷スクランブル交差点",
    description: "The world's busiest pedestrian crossing and the iconic Hachiko dog statue. A must-see Tokyo landmark.",
    category: "landmark",
    area: "tokyo",
    lat: 35.6595,
    lng: 139.7004,
    address: "Shibuya, Tokyo",
    photoUrls: [],
    avgDurationMin: 30,
  },
  {
    id: "spot-shibuya-sky",
    nameEn: "Shibuya Sky",
    nameJa: "渋谷スカイ",
    description: "An open-air observation deck on the 46th floor of Shibuya Scramble Square, offering 360-degree views of Tokyo.",
    category: "observation",
    area: "tokyo",
    lat: 35.6580,
    lng: 139.7022,
    address: "Shibuya Scramble Square, 2-24-12 Shibuya, Tokyo",
    photoUrls: [],
    admissionFee: "¥2,000",
    avgDurationMin: 60,
  },
  {
    id: "spot-fuunji",
    nameEn: "Fuunji Tsukemen",
    nameJa: "風雲児",
    description: "One of Tokyo's most famous tsukemen (dipping ramen) shops. Known for rich, flavorful broth and thick noodles.",
    category: "restaurant",
    area: "tokyo",
    lat: 35.6904,
    lng: 139.6977,
    address: "Yoyogi, Shibuya City, Tokyo",
    photoUrls: [],
    avgDurationMin: 45,
  },
  {
    id: "spot-teamlab",
    nameEn: "teamLab Borderless",
    nameJa: "チームラボ ボーダレス",
    description: "An immersive digital art museum where artworks move, flow, and blend into one another. A must-visit for art lovers.",
    category: "museum",
    area: "tokyo",
    lat: 35.6585,
    lng: 139.7380,
    address: "Azabudai Hills, Minato City, Tokyo",
    photoUrls: [],
    admissionFee: "¥3,800",
    avgDurationMin: 120,
  },
  {
    id: "spot-sensoji",
    nameEn: "Senso-ji Temple",
    nameJa: "浅草寺",
    description: "Tokyo's oldest temple, featuring the iconic Kaminarimon gate and Nakamise shopping street.",
    category: "temple",
    area: "tokyo",
    lat: 35.7148,
    lng: 139.7967,
    address: "2-3-1 Asakusa, Taito City, Tokyo",
    photoUrls: [],
    admissionFee: "Free",
    avgDurationMin: 60,
  },
  {
    id: "spot-akihabara",
    nameEn: "Akihabara Electric Town",
    nameJa: "秋葉原",
    description: "The epicenter of anime, manga, and electronics culture. Endless shops for otaku goods and tech gadgets.",
    category: "shopping",
    area: "tokyo",
    lat: 35.7023,
    lng: 139.7745,
    address: "Sotokanda, Chiyoda City, Tokyo",
    photoUrls: [],
    avgDurationMin: 120,
  },
  {
    id: "spot-tsukiji",
    nameEn: "Tsukiji Outer Market",
    nameJa: "築地場外市場",
    description: "A bustling food market with fresh sushi, tamagoyaki, seafood snacks, and kitchen supplies.",
    category: "market",
    area: "tokyo",
    lat: 35.6654,
    lng: 139.7707,
    address: "Tsukiji, Chuo City, Tokyo",
    photoUrls: [],
    avgDurationMin: 90,
  },
  {
    id: "spot-skytree",
    nameEn: "Tokyo Skytree",
    nameJa: "東京スカイツリー",
    description: "At 634m, it's the tallest tower in the world. Two observation decks offer breathtaking views of the city.",
    category: "observation",
    area: "tokyo",
    lat: 35.7101,
    lng: 139.8107,
    address: "1-1-2 Oshiage, Sumida City, Tokyo",
    photoUrls: [],
    admissionFee: "¥2,100",
    avgDurationMin: 60,
  },
  {
    id: "spot-shinjuku-gyoen",
    nameEn: "Shinjuku Gyoen",
    nameJa: "新宿御苑",
    description: "A beautiful park with Japanese, English, and French gardens. One of Tokyo's best cherry blossom spots.",
    category: "park",
    area: "tokyo",
    lat: 35.6852,
    lng: 139.7100,
    address: "11 Naitocho, Shinjuku City, Tokyo",
    photoUrls: [],
    admissionFee: "¥500",
    avgDurationMin: 90,
  },
  {
    id: "spot-imperial-palace",
    nameEn: "Imperial Palace Gardens",
    nameJa: "皇居外苑",
    description: "The grounds surrounding the Imperial Palace, with beautiful gardens and historic stone walls.",
    category: "park",
    area: "tokyo",
    lat: 35.6852,
    lng: 139.7528,
    address: "1-1 Chiyoda, Chiyoda City, Tokyo",
    photoUrls: [],
    admissionFee: "Free",
    avgDurationMin: 60,
  },
];

// ===== Helper: get spot by id =====
export function getSpotById(id: string): Spot | undefined {
  return SAMPLE_SPOTS.find((s) => s.id === id);
}

// ===== SAMPLE ITINERARIES =====

function buildItems(dayId: string, spotConfigs: { spotId: string; startTime: string; durationMinutes: number; note?: string; transport?: ItineraryItem["transportToNext"] }[]): ItineraryItem[] {
  return spotConfigs.map((config, index) => ({
    id: `${dayId}-item-${index}`,
    dayId,
    spotId: config.spotId,
    spot: getSpotById(config.spotId)!,
    orderIndex: index,
    startTime: config.startTime,
    durationMinutes: config.durationMinutes,
    note: config.note,
    transportToNext: config.transport,
  }));
}

const day1Items = buildItems("day-1", [
  { spotId: "spot-meiji", startTime: "09:00", durationMinutes: 60, note: "Arrive early for a peaceful experience before the crowds. Walk through the torii gate tunnel — it's stunning in the morning light.", transport: { mode: "walk", durationMinutes: 12 } },
  { spotId: "spot-takeshita", startTime: "10:15", durationMinutes: 75, note: "Don't miss the crepe shops and quirky fashion boutiques. Try a rainbow cotton candy from Totti Candy Factory.", transport: { mode: "train", durationMinutes: 8, detail: "JR Yamanote Line" } },
  { spotId: "spot-shibuya", startTime: "11:45", durationMinutes: 30, note: "For the best overhead view of the crossing, head to the Starbucks on the 2nd floor of TSUTAYA building.", transport: { mode: "walk", durationMinutes: 5 } },
  { spotId: "spot-shibuya-sky", startTime: "12:30", durationMinutes: 60, note: "Book tickets online in advance — it's cheaper and you skip the line. On clear days, you can see Mt. Fuji.", transport: { mode: "train", durationMinutes: 15 } },
  { spotId: "spot-fuunji", startTime: "14:00", durationMinutes: 45, note: "One of Tokyo's best tsukemen spots. Order from the vending machine — the regular tsukemen is the way to go.", transport: { mode: "train", durationMinutes: 20 } },
  { spotId: "spot-teamlab", startTime: "15:30", durationMinutes: 120, note: "Book tickets well in advance. Wear white clothing if possible — the art projections look amazing on white fabric." },
]);

const day2Items = buildItems("day-2", [
  { spotId: "spot-sensoji", startTime: "09:00", durationMinutes: 60, note: "Get there early before the crowds. Walk through Nakamise shopping street for souvenirs and snacks.", transport: { mode: "walk", durationMinutes: 5 } },
  { spotId: "spot-tsukiji", startTime: "10:30", durationMinutes: 90, note: "Must-try: fresh sushi, tamagoyaki (egg omelette), and grilled seafood skewers.", transport: { mode: "train", durationMinutes: 15 } },
  { spotId: "spot-akihabara", startTime: "13:00", durationMinutes: 120, note: "Even if you're not into anime, the multi-story electronics shops and maid cafes are a unique cultural experience.", transport: { mode: "train", durationMinutes: 10 } },
  { spotId: "spot-skytree", startTime: "16:00", durationMinutes: 60, note: "Time your visit for sunset — the city view transitions from daylight to illuminated Tokyo." },
]);

const proItinerary: Itinerary = {
  id: "itinerary-tokyo-classic",
  userId: "user-ken",
  title: "Classic Tokyo: Culture, Food & City Life",
  description: "My go-to recommendation for first-time visitors to Tokyo. This 5-day itinerary covers the essential highlights while leaving room for spontaneous exploration.",
  area: "tokyo",
  durationDays: 5,
  startDate: "2026-03-25",
  status: "published",
  isPro: true,
  tags: ["Culture", "Food", "Shopping", "First-timers", "Art"],
  viewCount: 2438,
  createdAt: "2026-03-01",
  updatedAt: "2026-03-20",
  author: {
    id: "user-ken",
    email: "ken@journeyjpn.com",
    displayName: "Ken",
    isPro: true,
  },
  days: [
    { id: "day-1", itineraryId: "itinerary-tokyo-classic", dayNumber: 1, date: "2026-03-25", title: "Harajuku, Shibuya & Digital Art", items: day1Items },
    { id: "day-2", itineraryId: "itinerary-tokyo-classic", dayNumber: 2, date: "2026-03-26", title: "Asakusa, Tsukiji & Akihabara", items: day2Items },
    { id: "day-3", itineraryId: "itinerary-tokyo-classic", dayNumber: 3, title: "Tsukiji, Ginza & Odaiba", items: [] },
    { id: "day-4", itineraryId: "itinerary-tokyo-classic", dayNumber: 4, title: "Shinjuku, Kabukicho & Golden Gai", items: [] },
    { id: "day-5", itineraryId: "itinerary-tokyo-classic", dayNumber: 5, title: "Yanaka, Nezu & Hidden Tokyo", items: [] },
  ],
};

export const SAMPLE_ITINERARIES: Itinerary[] = [
  proItinerary,
  {
    id: "itinerary-tokyo-golden",
    userId: "user-ken",
    title: "Tokyo + Kyoto Golden Route",
    description: "The classic 7-day route combining the best of Tokyo's modern energy with Kyoto's traditional beauty.",
    area: "tokyo",
    durationDays: 7,
    status: "published",
    isPro: true,
    tags: ["Temple", "History", "Food"],
    viewCount: 3102,
    createdAt: "2026-02-15",
    updatedAt: "2026-03-18",
    author: { id: "user-ken", email: "ken@journeyjpn.com", displayName: "Ken", isPro: true },
    days: [],
  },
  {
    id: "itinerary-anime-weekend",
    userId: "user-mike",
    title: "Tokyo Anime & Gaming Weekend",
    description: "A 3-day deep dive into Tokyo's anime, manga, and gaming scene.",
    area: "tokyo",
    durationDays: 3,
    status: "published",
    isPro: false,
    tags: ["Anime", "Gaming", "Akihabara"],
    viewCount: 890,
    createdAt: "2026-03-10",
    updatedAt: "2026-03-15",
    author: { id: "user-mike", email: "mike@example.com", displayName: "Mike from LA", isPro: false },
    days: [],
  },
  {
    id: "itinerary-food-lover",
    userId: "user-ken",
    title: "Tokyo Food Lover's Itinerary",
    description: "4 days of the best food Tokyo has to offer — from Michelin-star sushi to standing ramen bars.",
    area: "tokyo",
    durationDays: 4,
    status: "published",
    isPro: true,
    tags: ["Sushi", "Ramen", "Street Food"],
    viewCount: 1832,
    createdAt: "2026-02-20",
    updatedAt: "2026-03-12",
    author: { id: "user-ken", email: "ken@journeyjpn.com", displayName: "Ken", isPro: true },
    days: [],
  },
  {
    id: "itinerary-family-trip",
    userId: "user-sarah",
    title: "Family Trip: Tokyo, Hakone & Kyoto",
    description: "A kid-friendly 10-day journey through Japan's highlights with plenty of rest days built in.",
    area: "tokyo",
    durationDays: 10,
    status: "published",
    isPro: false,
    tags: ["Family", "Nature", "Culture"],
    viewCount: 1205,
    createdAt: "2026-03-05",
    updatedAt: "2026-03-19",
    author: { id: "user-sarah", email: "sarah@example.com", displayName: "Sarah from NYC", isPro: false },
    days: [],
  },
  {
    id: "itinerary-48hrs-shibuya",
    userId: "user-james",
    title: "48 Hours in Shibuya & Shinjuku",
    description: "A fast-paced weekend in Tokyo's two most energetic neighborhoods.",
    area: "tokyo",
    durationDays: 2,
    status: "published",
    isPro: false,
    tags: ["Nightlife", "Shopping"],
    viewCount: 650,
    createdAt: "2026-03-12",
    updatedAt: "2026-03-17",
    author: { id: "user-james", email: "james@example.com", displayName: "James from London", isPro: false },
    days: [],
  },
];
